# Generated by Django 3.2 on 2022-07-07 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('password_to_edit', models.CharField(blank=True, max_length=2000, null=True)),
                ('password_to_read', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
